### ISSUE TITLE
Adding attributes dynamically

### ISSUE THREAD

**Issue by bent10** [posthtml/posthtml-components#65]
I'm looking to dynamically add attributes in a component. For example, consider the following component code:

```html
<!-- src/components/foo.html -->
<script props>
  let classes = 'btn-foo'

  if (props.active) {
    classes += ' active'

    // Include this prop when the 'active' attribute is defined
    props['aria-pressed'] = true // ??
  }

  module.exports = { classes }
</script>

<button type="button" class="{{classes}}">
  <yield />
</button>
```

**Usage:**

```html
<x-foo>Hit me!</x-foo>
<x-foo active>Hit me too!</x-foo>
```

**Expected result:**

```html
<button type="button" class="btn-foo">Hit me!</button>
<button type="button" class="btn-foo active" aria-pressed="true">Hit me too!</button>
```

Is there a way to achieve the addition of these dynamic attributes? Thanks!

**Comment by thewebartisan7** [comment]
When an attribute has a value of "null" or "undefined" then it's removed, see here https://github.com/posthtml/posthtml-components/blob/main/src/index.js#L232-L242

This was added for boolean attributes like `disabled` or `selected`, since we can't set `disabled="false"`.

So in your case it would be something like:

```html
<!-- src/components/foo.html -->
<script props>
  let classes = 'btn-foo'

  if (props.active) {
    classes += ' active'
  }

  module.exports = { 
     classes,
     pressed: active ? 'true' : undefined // or null
 }
</script>

<button type="button" class="{{classes}}" aria-pressed="{{pressed}}">
  <yield />
</button>
```

or also simpler:

```html
<button type="button" class="btn-foo {{active ? 'active' : ''}}" aria-pressed="{{active ? 'true' : undefined}}">
  <yield />
</button>
```

**Comment by thewebartisan7** [comment]
Your name and avatar are familiar to me. Are you the author of the Looper template?

**Comment by bent10** [comment]
Yes, I'm 😅

Thank you for your prompt response and detailed information 💯 

As additional information, if someone encounters a similar issue and receives an error message like `ReferenceError: 'pressed' is not defined` when using `posthtml-expressions@v1.11.x`, the solution is to add the following configuration:

```js
posthtml()
  .use(components({
    expressions: { missingLocal: null },
    // ...
  }))
```

Include the above configuration will help resolve the undefined reference issue.

**Comment by thewebartisan7** [comment]
Looper is one of my preferred admin theme. I hope to see `posthtml-components` instead of Pug in the next update or in some of your other templates.

> As additional information, if someone encounters a similar issue and receives an error message like ReferenceError: 'pressed' is not defined when using posthtml-expressions@v1.11.x, the solution is to add the following configuration

I didn't know about this options, maybe is something new. Usually I do a check using `typeof myprop !== 'undefined'` which will not throw that error. Or you can set a default value in `script` tag.

```
<script props>
  module.exports = { 
     maybeUndefined: props.maybeUndefined ?? 'default'
    // or using underscore
    maybeUndefined: isUndefined(props.maybeUndefined) ? 'default' : props.maybeUndefined 
 }
</script>
```
