### ISSUE TITLE
Slots do not work when passed as the content to a component

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-components#70]
**example.html**

```xml
<x-card>
  <fill:cta>Stuff</fill:cta>
</x-card>
```

**card.html**

```xml
<x-button>
  <slot:cta />
<x-button>
```

**button.html**

```xml
<div>
  <yield />
</div>
```

The compiled example.html is:

```html
<div><div></div></div>
```

**Comment by thewebartisan7** [comment]
That's correct, there are several others way to handle this scenario, for example by passing Stuff as prop.

Can you share the whole code of card.html and button.html and how you are actually using them?

**Comment by cossssmin** [comment]
That’s all the code in those files.

Should this not render this instead?

```html
<div>
  Stuff
</div>
```

**Comment by thewebartisan7** [comment]
No because a `<slot/>` and `<fill/>` belong to a compoent, and can't contain other component or being nested inside a component.

For example this will not work:

`slot` of another component inside a component:

```xml
<x-button>
  <slot:cta />
<x-button>
```

or a component inside `fill`:

```xml
<x-card>
  <fill:cta>
    <x-button>Stuff</x-button>
  </fill:cta>
</x-card>
```


because the "context" of a component being processed, start from over, and doesn't know about `slot:cta` anymore. This is also good, because your slot doesn't need to have unique name for each component. I remember about trying to solve this, by creating a unique slot name on runtime, see https://github.com/posthtml/posthtml-components/commit/25259ef0f0833d5a460e541d8ed7e21de52f7d75 but this actually add additional issues. Also other template engine like Blade have same behaviour. Just when you think of slots and fills tag, remind that their context belong to one component. I never found this a problem, and you can always find an elegant solutions that solve your problem with props or splitting components into small components.

You could archive the same with prop in your example:

**example.html**

```xml
<x-card cta="Stuff"></x-card>
```

**card.html**

```xml
<script props>
  module.exports = {
    cta: props.cta
  };
</script>
<x-button>{{cta}}</x-button>
```

**button.html**

```xml
<button>
  <yield />
</button>
```

And for this case below:

```xml
<x-card>
  <fill:cta>
    <x-button>Stuff</x-button>
  </fill:cta>
</x-card>
```

you can split components into small components as shown here https://posthtml.github.io/posthtml-components/docs.html#splitting-component-in-small-component

Maybe your scenario is a bit different, since why x-card component just include x-button component? For this reasons I asked to share whole code, to find a better solution. Let me know if above make sense to you.

**Comment by cossssmin** [comment]
Thanks for the thorough explanation Damir, appreciate it! 

The question was raised in an [issue in Maizzle](https://github.com/maizzle/framework/issues/1100), so I took the example and simplified it for reproduction.
